arena_camera_node_fl:
  ros__parameters:
    camera_name: "camera_fl"
    frame_id: "CAMERA_FL"
    pixel_format: rgb8
    serial_no: 231400023
    camera_info_url: "package://lucid_vision_driver/config/camera_fl.yaml"
    fps: 15
    horizontal_binning: 1 # resize horizontal resolution/horizontal_binning
    vertical_binning: 1   # resize horizontal resolution/vertical_binning
    enable_rectifying: false
    enable_compressing: false
    use_default_device_settings: false
    # if you use_default_device_settings: true, the following settings are ignored.
    # ROS driver will use the default device settings of the camera.
    exposure_auto: true
    exposure_target: 187
    gain_auto: true
    gain_target: 1
    gamma_target: 1.0
    image_horizontal_flip: false
    image_vertical_flip: false

arena_camera_node_fr:
  ros__parameters:
    camera_name: "camera_fr"
    frame_id: "CAMERA_FR"
    pixel_format: rgb8
    serial_no: 232301929
    camera_info_url: "package://lucid_vision_driver/config/camera_fr.yaml"
    fps: 15
    horizontal_binning: 1 # resize horizontal resolution/horizontal_binning
    vertical_binning: 1   # resize horizontal resolution/vertical_binning
    enable_rectifying: false
    enable_compressing: false
    use_default_device_settings: false
    # if you use_default_device_settings: true, the following settings are ignored.
    # ROS driver will use the default device settings of the camera.
    exposure_auto: true
    exposure_target: 187
    gain_auto: true
    gain_target: 1
    gamma_target: 1.0
    image_horizontal_flip: false
    image_vertical_flip: false

arena_camera_node_rl:
  ros__parameters:
    camera_name: "camera_rl"
    frame_id: "CAMERA_RL"
    pixel_format: rgb8
    serial_no: 233500645
    camera_info_url: "package://lucid_vision_driver/config/camera_rl.yaml"
    fps: 15
    horizontal_binning: 1 # resize horizontal resolution/horizontal_binning
    vertical_binning: 1   # resize horizontal resolution/vertical_binning
    enable_rectifying: false
    enable_compressing: false
    use_default_device_settings: false
    # if you use_default_device_settings: true, the following settings are ignored.
    # ROS driver will use the default device settings of the camera.
    exposure_auto: true
    exposure_target: 187
    gain_auto: true
    gain_target: 1
    gamma_target: 1.0
    image_horizontal_flip: false
    image_vertical_flip: false

arena_camera_node_rr:
  ros__parameters:
    camera_name: "camera_rr"
    frame_id: "CAMERA_RR"
    pixel_format: rgb8
    serial_no: 233100071
    camera_info_url: "package://lucid_vision_driver/config/camera_rr.yaml"
    fps: 15
    horizontal_binning: 1 # resize horizontal resolution/horizontal_binning
    vertical_binning: 1   # resize horizontal resolution/vertical_binning
    enable_rectifying: false
    enable_compressing: false
    use_default_device_settings: false
    # if you use_default_device_settings: true, the following settings are ignored.
    # ROS driver will use the default device settings of the camera.
    exposure_auto: true
    exposure_target: 187
    gain_auto: true
    gain_target: 1
    gamma_target: 1.0
    image_horizontal_flip: false
    image_vertical_flip: false
